//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RabbitMQLibrary.Queries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SchedulingQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SchedulingQueries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RabbitMQLibrary.Queries.SchedulingQueries", typeof(SchedulingQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use RabbitMQ
        ///select MessageRunGuid, ScheduledMessageGuid, SendAttemptTime, SentSuccessfully from MessageRuns where ScheduledMessageGuid =@ScheduledMessageGuid.
        /// </summary>
        internal static string GetMessageRuns {
            get {
                return ResourceManager.GetString("GetMessageRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use RabbitMQ
        ///Select ScheduledMessageGuid, Active, m.MessageGuid, Body,
        ///RoutingKey, ms.MessageScheduleGuid, CronExpression, EffectiveDate,
        ///e.ExchangeGuid, ExchangeName, ExchangeType, Durable, AutoDelete
        ///from ScheduledMessages sm join Messages m on m.MessageGuid = sm.MessageGuid
        ///join MessageSchedules ms on sm.MessageScheduleGuid = ms.MessageScheduleGuid
        ///join Exchanges e on e.ExchangeGuid = sm.ExchangeGuid.
        /// </summary>
        internal static string GetScheduledMessages {
            get {
                return ResourceManager.GetString("GetScheduledMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MessageGuid, MessageScheduleGuid, ExchangeGuid.
        /// </summary>
        internal static string GetScheduledMessagesSplitOn {
            get {
                return ResourceManager.GetString("GetScheduledMessagesSplitOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use RabbitMQ
        ///INSERT MessageRuns(MessageRunGuid, ScheduledMessageGuid, SendAttemptTime, SentSuccessfully) Values(@MessageRunGuid, @ScheduledMessageGuid, @SendAttemptTime, @SendSuccessfully).
        /// </summary>
        internal static string InsertMessageRun {
            get {
                return ResourceManager.GetString("InsertMessageRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use RabbitMQ
        ///INSERT MessageRunErrors(MessageRunGuid, Error) Values(@MessageRunGuid, @Error).
        /// </summary>
        internal static string InsertMessageRunError {
            get {
                return ResourceManager.GetString("InsertMessageRunError", resourceCulture);
            }
        }
    }
}
